In [11]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:65% !important; }</style>"))

In [1]:
import pandas as pd
import numpy as np

This notebook will be used to create working data sets and .csv files for use in the LP optimization model.

In [2]:
# Read .csv
log = pd.read_csv('data/Sim data/sim_log_unlcap.csv', index_col=[0])

C:\Users\GijsTempelman\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [39]:
log

,Time,Machine,State,Set speed,Actual speed,Count,Tailback,Lack,Simulation
0,0.0,All,Simulation start,0.0,0.0,0.0,0,0,1.0
1,0.0,Depalletizer,128,6000.0,6000.0,6000.0,0,0,1.0
2,0.0,Filler,128,1291.0,1291.0,1291.0,0,0,1.0
3,0.0,Pasteurizer,128,720.0,720.0,720.0,0,0,1.0
4,0.0,Labeler_1,128,333.0,333.0,333.0,0,0,1.0
...,...,...,...,...,...,...,...,...,...
43299995,480.0,Labeler_2,128,580.0,580.0,219711.0,0,0,10000.0
43299996,480.0,GPI,128,1200.0,666.0,261668.0,0,1,10000.0
43299997,480.0,SN64,128,510.0,510.0,261334.0,0,0,10000.0
43299998,480.0,Palletizer_1,128,1200.0,510.0,126935.0,0,1,10000.0
43299999,480.0,Palletizer_2,128,0.0,0.0,134399.0,0,0,10000.0

In [43]:
df_lp = pd.DataFrame()

In [44]:
df_lp[['Time', 'Simulation', 'Depalletizer']] = log[['Time', 'Simulation', 'Actual speed']][(log['Machine'] == 'Depalletizer')].reset_index(drop = True)
df_lp['Filler'] = log['Actual speed'][(log['Machine'] == 'Filler')].reset_index(drop = True)
df_lp['Pasteurizer'] = log['Actual speed'][(log['Machine'] == 'Pasteurizer')].reset_index(drop = True)
df_lp['Labeler'] = log['Actual speed'][(log['Machine'] == 'Labeler_1')].reset_index(drop = True) + log['Actual speed'][(log['Machine'] == 'Labeler_2')].reset_index(drop = True)
df_lp['GPI'] = log['Actual speed'][(log['Machine'] == 'GPI')].reset_index(drop = True)
df_lp['SN64'] = log['Actual speed'][(log['Machine'] == 'SN64')].reset_index(drop = True)
df_lp['Palletizer'] = log['Actual speed'][(log['Machine'] == 'Palletizer_1')].reset_index(drop = True) + log['Actual speed'][(log['Machine'] == 'Palletizer_2')].reset_index(drop = True)

In [45]:
df_lp

,Time,Simulation,Depalletizer,Filler,Pasteurizer,Labeler,GPI,SN64,Palletizer
0,0.0,1.0,6000.0,1291.0,720.0,720.0,420.0,420.0,420.0
1,1.0,1.0,7200.0,630.0,660.0,660.0,600.0,0.0,0.0
2,2.0,1.0,7200.0,630.0,0.0,0.0,360.0,660.0,660.0
3,3.0,1.0,6000.0,630.0,720.0,587.0,0.0,300.0,0.0
4,4.0,1.0,7200.0,1291.0,780.0,913.0,420.0,0.0,300.0
...,...,...,...,...,...,...,...,...,...
4809995,476.0,10000.0,8400.0,1291.0,600.0,666.0,840.0,540.0,540.0
4809996,477.0,10000.0,8400.0,833.0,600.0,580.0,658.0,540.0,540.0
4809997,478.0,10000.0,7200.0,1291.0,540.0,345.0,0.0,780.0,780.0
4809998,479.0,10000.0,7200.0,630.0,600.0,581.0,840.0,720.0,720.0
4809999,480.0,10000.0,7200.0,1291.0,660.0,580.0,666.0,510.0,510.0

In [46]:
df_lp.to_csv('data/LP data/df_lp.csv', index = False)

In [37]:
df_sim1 = df_lp[df_lp['Simulation'] == 1]
df_sim1.to_csv('data/LP data/sim1.csv', index = False)